изменили yml

diff --git a/.github/workflows/api-tests.yml b/.github/workflows/api-tests.yml
--- a/.github/workflows/api-tests.yml
+++ b/.github/workflows/api-tests.yml
@@ -6,3 +6,23 @@ on:
 jobs:
   build:
     uses: yandex-praktikum/java-filmorate/.github/workflows/api-tests.yml@ci
+    check-branch:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Check branch
+          run: |
+            if [[ "$GITHUB_HEAD_REF" == "add-common-films" || 
+                  "$GITHUB_HEAD_REF" == "add-director" || 
+                  "$GITHUB_HEAD_REF" == "add-feed" || 
+                  "$GITHUB_HEAD_REF" == "add-marks" || 
+                  "$GITHUB_HEAD_REF" == "add-most-populars" || 
+                  "$GITHUB_HEAD_REF" == "add-recommendations" || 
+                  "$GITHUB_HEAD_REF" == "add-remove-endpoint" || 
+                  "$GITHUB_HEAD_REF" == "add-reviews" || 
+                  "$GITHUB_HEAD_REF" == "add-search" ]]; then
+                echo "Valid branch"
+                # Здесь поместите команду для объединения pull request
+            else
+                echo "Invalid branch"
+                exit 1
+            fi
